# config.yaml
# Configuration for the NCBI data download script.
# Defines where to save retrieved viroporin sequences, the output FASTA file,
# your NCBI Entrez contact email and API key, and how many records to request.
# Used to automatically fetch and store viral membrane protein sequences.

out: data/viroporins_balanced_ncbi.fasta
dir: data/viroporin_families_ncbi
entrez_email: seyednima.morsali@sjsu.edu
ncbi_api_key: 087f8ba753422869d5961bdc75edc5efb609
ncbi_retmax: 200000